- name: Install main vhost into nginx
  template:
    src: templates/web.ratzek.conf.j2
    dest: /etc/nginx/sites-enabled/web.ratzek.conf
  notify:
    - Restart nginx

- name: Create /var/www/library directory
  file:
    path: "{{ ratzek_portal__library_path }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"

- name: Create /var/www/webcam_archive directory
  file:
    path: "{{ ratzek_portal__webcam_archive_path }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"

- name: Create /var/www/webcam_daily_archive directory
  file:
    path: "{{ ratzek_portal__webcam_daily_archive_path }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"

- name: "Add cronjob which downloads webcam shots"
  ansible.builtin.cron:
    name: get_webcam_picture
    hour: '*'
    minute: '*/5'
    job: "/usr/bin/wget -q -O {{ ratzek_portal__webcam_archive_path }}/$(date +'\\%F__\\%T').jpg 'http://{{ ratzek_portal__webcam_user }}:{{ ratzek_portal__webcam_password }}@10.11.3.4/ISAPI/Streaming/channels/101/picture'"

- name: "Add cronjob which saved forever daily webcam image"
  ansible.builtin.cron:
    name: store_forever_webcam_picture
    hour: '14'
    minute: '1'
    job: "find {{ ratzek_portal__webcam_archive_path }}/ -name '*.jpg' -type f -mmin -5 -exec ln {} {{ ratzek_portal__webcam_daily_archive_path }}/ ';'"

- name: "Add cronjob which deletes old webcam shots"
  ansible.builtin.cron:
    name: get_webcam_picture_cleanup
    hour: '21'
    minute: 0
    job: "find {{ ratzek_portal__webcam_archive_path }}/ -type f -name '*.jpg' -mtime +14 -delete"

- name: Install grafana vhost into nginx
  template:
    src: templates/grafana.ratzek.conf.j2
    dest: /etc/nginx/sites-enabled/grafana.ratzek.conf
  notify:
    - Restart nginx

- name: Install captive portal into nginx
  template:
    src: templates/captive-portal.conf.j2
    dest: /etc/nginx/sites-enabled/captive-portal.conf
  notify:
    - Restart nginx

- ansible.builtin.include_role:
    name: ansible-role-minidlna

- name: Install ratzek-services-frontend
  ansible.builtin.command:
    cmd: "git clone https://github.com/ala-archa/ratzek-services-frontend /var/www/ratzek-portal"
    creates: /var/www/ratzek-portal
