- name: Install main vhost into nginx
  template:
    src: templates/web.ratzek.conf.j2
    dest: /etc/nginx/sites-enabled/web.ratzek.conf
  notify:
    - Restart nginx

- name: Create /var/www/library directory
  file:
    path: "{{ ratzek_portal__library_path }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"

- name: Install grafana vhost into nginx
  template:
    src: templates/grafana.ratzek.conf.j2
    dest: /etc/nginx/sites-enabled/grafana.ratzek.conf
  notify:
    - Restart nginx

- name: Install captive portal into nginx
  template:
    src: templates/captive-portal.conf.j2
    dest: /etc/nginx/sites-enabled/captive-portal.conf
  notify:
    - Restart nginx

- ansible.builtin.include_role:
    name: ansible-role-minidlna

- name: Install ratzek-services-frontend
  ansible.builtin.command:
    cmd: "git clone https://github.com/ala-archa/ratzek-services-frontend /var/www/ratzek-portal"
    creates: /var/www/ratzek-portal
