
- name: Install nginx
  become: true
  package:
    name: nginx
    state: present
  notify:
    - Restart nginx

- name: Install nginx fancyindex
  become: true
  package:
    name: libnginx-mod-http-fancyindex
    state: present
  notify:
    - Restart nginx

- name: Remove default nginx host
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Configure nginx
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - Restart nginx

- name: Configure logrotate for
  template:
    src: templates/nginx-logrotate.conf.j2
    dest: /etc/logrotate.d/nginx
  # # TODO
  # notify:
  #   - Restart nginx

- name: Enable nginx
  become: true
  service:
    name: nginx
    enabled: true
