
- name: Restart netfilter-persistent
  become: true
  service:
    name: netfilter-persistent
    state: restarted

- name: Restart ratzek-services-http-backend
  become: true
  service:
    name: ratzek-services-http-backend
    state: restarted
