
- name: Install docker
  become: true
  package:
    name: docker
    state: present

- name: Install docker-compose
  become: true
  package:
    name: docker-compose
    state: present

- name: Check for postgres directory exists
  stat:
    path: "{{ lemmy_directory }}/volumes/postgres"
  register: postgres

- name: "Create {{ lemmy_directory }} directory"
  when: not postgres.stat.exists
  file:
    path: "{{ lemmy_directory }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"

- name: "Create {{ lemmy_directory }}/volumes/pictrs directory"
  when: not postgres.stat.exists
  file:
    path: "{{ lemmy_directory }}/volumes/pictrs"
    state: "directory"
    owner: "991"
    group: "991"
    mode: "0755"

- name: Install docker-compose.yml
  when: not postgres.stat.exists
  template:
    src: templates/docker-compose.yml.j2
    dest: "{{ lemmy_directory }}/docker-compose.yml"

- name: Install lemmy.hjson
  when: not postgres.stat.exists
  template:
    src: templates/lemmy.hjson.j2
    dest: "{{ lemmy_directory }}/lemmy.hjson"

- name: Install vhost into Nginx
  when: not postgres.stat.exists
  template:
    src: templates/lemmy.conf.j2
    dest: /etc/nginx/sites-enabled/lemmy.conf

- name: Start lemmy container
  when: not postgres.stat.exists
  command: "chdir={{ lemmy_directory }} docker-compose up -d"
