
- ansible.builtin.include_role:
    name: systemd-journald
  vars:
    journald_config:
      Storage: volatile
      RuntimeMaxUse: 8M
    journald_wipe_persistent: true

- name: Store logs on tmpfs
  ansible.posix.mount:
    path: /var/log
    src: tmpfs
    fstype: tmpfs
    opts: auto,size=64m
    state: mounted
  notify:
    - Restart rsyslog

- name: Store nginx logs on tmpfs
  ansible.posix.mount:
    path: /var/log/nginx
    src: tmpfs
    fstype: tmpfs
    opts: auto,size=64m
    state: mounted
  notify:
    - Restart nginx

- name: Tune vm.dirty_background_ratio
  sysctl:
    name: vm.dirty_background_ratio
    value: 20
    state: present
    reload: yes

- name: Tune vm.dirty_expire_centisecs
  sysctl:
    name: vm.dirty_expire_centisecs
    value: 30000
    state: present
    reload: yes

- name: Tune vm.dirty_writeback_centisecs
  sysctl:
    name: vm.dirty_writeback_centisecs
    value: 30000
    state: present
    reload: yes
