
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Upgrade all apt packages
  apt: upgrade=dist force_apt_get=yes

- name: Install useful admin tools
  apt:
    pkg:
      - vim
      - strace
      - lsof
      - tcpdump
      - git
      - socat
      - nmap
      - rsync
      - wget
      - curl
      - tar
      - procps
      - psmisc
      - ripgrep
      - sed
      - perl
      - hdparm
      - smartmontools
      - iotop
      - dnsutils
