
- name: Install openvpn
  become: true
  package:
    name: openvpn
    state: present
  notify:
    - Restart openvpn-client

- name: Configure openvpn-client
  copy:
    content: "{{ openvpn_client_config }}"
    dest: /etc/openvpn/client.ovpn
  notify:
    - Restart openvpn-client

- name: Configure openvpn-client systemd service
  copy:
    src: vpn-client.service
    dest: /etc/systemd/system/openvpn-client.service
  notify:
    - Restart openvpn-client

- name: Enable openvpn-client
  become: true
  service:
    name: openvpn-client
    enabled: true

- name: Monitor VPN connection via cron
  ansible.builtin.cron:
    name: Monitor VPN connection
    hour: "*"
    minute: "*/5"
    job: "ping -w1 -c1 10.8.0.1 >/dev/null 2>&1 || systemctl restart openvpn-client.service"
