
# FIXME: For some reason Ansible cannot determine interface state correctly
- ansible.builtin.include_role:
    name: ansible-role-interfaces

- ansible.builtin.include_role:
    name: ansible-role-dhcp

- ansible.builtin.include_role:
    name: ansible-hostapd

- name: Enabled IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: yes

- name: Install ipset
  become: true
  package:
    name: ipset
    state: present

- name: Install ipset-persistent
  become: true
  package:
    name: ipset-persistent
    state: present
  notify:
    - Restart netfilter-persistent

- name: Configure ipset
  template:
    src: templates/ipsets.j2
    dest: /etc/iptables/ipsets
  notify:
    - Restart netfilter-persistent

- name: Copy systemd unit file
  copy:
    src: "traffic-control.service"
    dest: "/etc/systemd/system/traffic-control.service"
    owner: "root"
    group: "root"
    mode: "0644"
  register: traffic_control_register_unit

- name: Generate tc script
  template:
    src: templates/access-point-tc-restore
    dest: /usr/bin/access-point-tc-restore
    owner: "root"
    group: "root"
    mode: "0755"
  register: traffic_control_register_script

- name: Reload systemd daemon
  command: "systemctl daemon-reload"
  when: traffic_control_register_unit is changed

- name: Restart tc service
  service:
    name: "traffic-control"
    state: "restarted"
    enabled: True
  when: traffic_control_register_script is changed

- ansible.builtin.include_role:
    name: ansible-iptables


- name: Check if wget is already installed
  stat:
    path: /usr/bin/wget
  register: wget_bin

- name: Install wget
  package:
    name: wget
    state: present
  become: true
  when: not wget_bin.stat.exists

- name: "Add cronjob which updates dynamic dns IP at afraid.org"
  ansible.builtin.cron:
    name: afraid_org_update
    hour: '*'
    minute: 1
    job: "/usr/bin/wget -q -O /dev/null --read-timeout=0.0 --waitretry=5 --tries=40 'https://freedns.afraid.org/dynamic/update.php?{{ afraid_org_token }}' >/dev/null 2>&1"

- name: Generate resolv.conf
  copy:
    content: |
      nameserver {{ access_point__nameserver }}
    dest: "/etc/resolv.conf"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Uninstall network-manager
  package:
    name: "network-manager"
    state: absent

- name: Install ratzek-services-http-backend
  ansible.builtin.command:
    cmd: "/usr/bin/wget -O /usr/bin/ratzek-services-http-backend 'https://github.com/ala-archa/ratzek-services-http-backend/releases/download/v{{ access_point__http_backend_version }}/ala-archa-http-backend'"
    creates: /usr/bin/ratzek-services-http-backend
  notify:
    - Restart ratzek-services-http-backend

- name: Change permission on ratzek-services-http-backend
  file:
    path: /usr/bin/ratzek-services-http-backend
    state: file
    owner: root
    group: root
    mode: 0755

- name: Configure ratzek-services-http-backend
  template:
    src: templates/ala-archa-http-backend.yaml.j2
    dest: /etc/ala-archa-http-backend.yaml
  notify:
    - Restart ratzek-services-http-backend

- name: Copy systemd unit file for http-backend
  copy:
    src: "ratzek-services-http-backend.service"
    dest: "/etc/systemd/system/ratzek-services-http-backend.service"
    owner: "root"
    group: "root"
    mode: "0644"
  register: ratzek_http_backend_register_unit
  notify:
    - Restart ratzek-services-http-backend

- name: Reload systemd daemon
  command: "systemctl daemon-reload"
  when: ratzek_http_backend_register_unit is changed
