
- name: Setup Ratzek RPI
  hosts: ratzek-service
  tasks:
    - name: Set a hostname
      ansible.builtin.hostname:
        name: "{{ domain_name }}"
      tags:
        - hostname
  roles:
    - role: common
      tags:
        - common
    - role: monitoring-server
      tags:
        - monitoring
    - role: ansible-role-bind
      tags:
        - bind
    - role: access-point
      tags:
        - access-point
    - role: youtube-mirror
    - role: lepikhin-guidebook-mirror
      tags: lepikhin-guidebook
    - role: mountain-forecast-mirror
      tags: mountain-forecast-mirror
    - role: weather-station
      tags: weather-station
    - role: ratzek-portal
      tags:
        - ratzek-portal
    - role: vpn-client
      tags:
        - vpn-client
    - role: mikrotik-exporter
      vars:
        mikrotik_exporter__version: 1.0.11
      tags:
        - mikrotik-exporter
  vars:
    ntp_timezone: Asia/Bishkek
    my_client_ip: 10.11.3.2
    my_client_ip_network: 10.11.3.0
    my_client_ip_netmask: 255.255.255.0
    my_client_ip_broadcast: 10.11.3.255
    my_client_ip_gateway: 10.11.3.1

    my_public_ip: 10.11.4.1
    my_public_ip_network: 10.11.4.0
    my_public_ip_netmask: 255.255.255.0
    my_public_ip_broadcast: 10.11.4.255
    my_public_dhcp_range_begin: 10.11.4.50
    my_public_dhcp_range_end: 10.11.4.255
    my_wlan1_mac: "30:de:4b:03:a9:89"

    domain_name: ratzek

    admin_username: evgenii
    admin_user_description: Evgenii Lepikhin
    admin_ssh_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAEAQC/CWhpAFmIYZf35K6CIA4aV39UqQYTwr8W+7C3lDxela411oiv3xd8I7motxOUfREZY70BtkvI8jS7/5TYLnUns4dPljm+rL1SjqWnJPFzhIgWj7ASqA+JUBL927Ns7cXoC6Yjj+qBBl181CwQqb5EVV15dKTZ+Gp7z8XYwt0HqqqPsokosYsSX8jR6QC3avxInL3uUJ1GXSWAk50bGp7TgwC6sqlrZRXv2SGQH2czfph8jbvLOt5YaPesTkiown3kzdWC5d9m6jeiY9hnP+b+qqF0OO1tJHb1afK4pLY9bMlXsAUZtmx240RtByMyK9f9WdXwu4AznHTu+muNR+NS7KtN2AuBr8a6I0ftoH68MwhawiZ8+OVKtAqeJehqZ3PlhZqjAJ7v4x4S1KDQlliusZRVZmxmdOkAAFdVk9qlqMxmPBsAaxtJGCCQNU1GxM05W4yu5jTU3O0WaYzmNAvkBIC+F0h83sTBwUk9jr1w0JkXqhegzkOwad5LD6ltDNDAiTOcgJ8IsNmaBxIYtWxHri5QPstwoqFz/J1rp50IsjBqWLzek7m6HoXjSaHoMyZDZ7so3DGmZdO2WK4GpUeuRVFpwO+9lB1kBclccqZUUZVu/k8S/1rVk1j4Q2mPGJ+/GHCwYVukLMh2lDZ5JdMBBnGK5XvS5JdD3hj1B/H1Lv/Cxl1Ofz9Y0ysC2Ok4Rvi2muO9W5v5cgcWRdJsR33xy4n83nC0ORKBn8diM9uCuw2+xmi3yIIPNG8LBk4sqYGwAYoesV1+5Ah7XbRbTzDdPd0G/UZ4GwvZpNIsFipwXOqkoWfOFYwvknIKXk+NOuZUSrKFLnjsoTn00HzzrM6xtOUu3VnDEzHmwAk45CWlnyuRKxDjG0td10+lSk20sFS0vRUZGeENbGwLtOEr5GrJqVJ4PSidb3DBlaKNYtdbPw+Sd+BYiFN+8iC87iB/0tCL425I6BbprRt9Y7w7+Ft2FRwpADPcapMjfKa8/WywqWedfo21lRCzNzmqeB0LAtpmcih/ZgUxHrBI0xKxYhLkvim0kI6QYrW6A3OtJT2/8i3S8de77jUScItDg6tdmmMMRIrJkJ6KEOxv/6zm/aFterhcTIt3ZF7twCRpipqrKgoj+RuaVOxFsErH3P9LDHwA9EH/MC+V+QxS7EKocg+SVSu/r6rvDJiEzKT3M/GbzpzyeRb5wjAIgYg1Up3d0NGpspDg07BywBnUrrdIzMchlbYxskH0Sdffy3Qui7/tRoRZ97moj4B5xYbBqMq65/horViOPN1aa7H5T7uuPGXYVNnJ0DO+SskNHo/PQlmDIaPKxm5AUnN/v61W8c/VaUXJrjvt4CG61HtSG01NkW2T Evgenii Lepikhin common key"
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCr964rJB9XPi3srqrDkcAh3Zh4wPy5c0bN+uc0E1Qi3dEHT4qFbxjruqVfxG5tcJIj5QpTbSsxWebmJzH2FkCIppOv2FwxFLS0smdAyPomqYcw+Z/on6O8BciesCDr3JwXpgIn98aK7/REmrw6ZmFkJMr9rO+9foo3vAdHRe0AJZZPPKoQp3lic3ET5Kx3wCeGaeZ6mBLxTou5zTkuHI17oF4oebAg5/GLWrxPb5KLc8FvFehxX/6mblQ75KjmRs5pbLZHEoAGTu9jrQ4jagZQQvx7hh+UWFhMSf2lIjEtqjF9pBimof+NBLboy6GpNFUuKu09kFtzRXVtY/s/c3Qv Evgenii Lepikhin mobile"

    pavlenko_video_directory: /var/mirrors/youtube/pavlenko

    node_exporter_web_listen_address: 127.0.0.1:9100

    prometheus_web_listen_address: 127.0.0.1:9090
    prometheus_targets:
      node:
        - targets:
            - '{{ node_exporter_web_listen_address }}'
      weather-station:
        - targets:
            - 127.0.0.1:9756
      mikrotik-exporter:
        - targets:
            - 127.0.0.1:9436
      ratzek-ap-exporter:
        - targets:
            - 127.0.0.1:8888
    prometheus_scrape_configs:
      - job_name: node
        file_sd_configs:
          - files:
              - "{{ prometheus_config_dir }}/file_sd/node.yml"
      - job_name: weather-station
        file_sd_configs:
          - files:
              - "{{ prometheus_config_dir }}/file_sd/weather-station.yml"
      - job_name: mikrotik-exporter
        file_sd_configs:
          - files:
              - "{{ prometheus_config_dir }}/file_sd/mikrotik-exporter.yml"
      - job_name: ratzek-ap-exporter
        file_sd_configs:
          - files:
              - "{{ prometheus_config_dir }}/file_sd/ratzek-ap-exporter.yml"
    prometheus_storage_retention: 1100d
    prometheus_global:
      scrape_interval: 60s
      scrape_timeout: 15s
      evaluation_interval: 15s

    grafana_address: 127.0.0.1
    grafana_port: 3000
    grafana_datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        url: 'http://{{ prometheus_web_listen_address }}'
        basicAuth: false
    grafana_security:
      admin_user: admin
      admin_password: '{{ grafana_admin_password }}'
    grafana_auth:
      anonymous:
        org_role: Viewer
        org_name: Ratzek public

    interfaces_ether_interfaces:
      - device: wlan1
        allowclass: allow-hotplug
        bootproto: static
        address: "{{ my_public_ip }}"
        netmask: "{{ my_public_ip_netmask }}"
        network: "{{ my_public_ip_network }}"
        broadcast: "{{ my_public_ip_broadcast }}"
      - device: eth0
        allowclass: allow-hotplug
        bootproto: static
        address: "{{ my_client_ip }}"
        netmask: "{{ my_client_ip_netmask }}"
        network: "{{ my_client_ip_network }}"
        broadcast: "{{ my_client_ip_broadcast }}"
        gateway: "{{ my_client_ip_gateway }}"

    bind_allow_query: ['any']
    bind_recursion: true
    bind_forwarders:
      - 8.8.8.8
      - 8.8.4.4
      - 9.9.9.9
      - 208.67.222.222
    bind_listen_ipv4: ['any']
    bind_zones:
      - name: "{{ domain_name }}"
        primaries:
          - "{{ my_public_ip }}"
        name_servers:
          - ns
        hosts:
          - name: www
            ip: "{{ my_public_ip }}"
          - name: grafana
            ip: "{{ my_public_ip }}"
          - name: forum
            ip: "{{ my_public_ip }}"
          - name: ns
            ip: "{{ my_public_ip }}"

    dhcp_global_domain_name_servers: "{{ my_public_ip }}"
    dhcp_global_domain_name: "{{ domain_name }}"
    dhcp_global_routers: "{{ my_public_ip }}"
    dhcp_global_server_name: "{{ domain_name }}"
    dhcp_subnets:
      - ip: "{{ my_public_ip_network }}"
        interface: wlan1
        netmask: 255.255.255.0
        range_begin: "{{ my_public_dhcp_range_begin }}"
        range_end: "{{ my_public_dhcp_range_end }}"
    dhcp_hosts:
      - name: ratzek-service
        ip: "{{ my_public_ip }}"
        mac: "{{ my_wlan1_mac }}"

    hostapd__service_configure_systemd: True
    hostapd__instances:
      client_ap:
        state: present
        interface: wlan1
        driver: nl80211
        ssid: ratzek-free
        country_code: US
        hw_mode: g
        channel: 6
        beacon_int: 100
        macaddr_acl: 0
        auth_algs: 1
        ignore_broadcast_ssid: 0
#        wpa: 2
#        wpa_passphrase: "{{ public_wpa_password }}"
        wpa_key_mgmt: WPA-PSK
        logger_syslog_level: 0
        ieee80211d: 1

    access_point__ipset_shaper: shaper
    # Раз в 3 часа сбрасывать счетчик рейтлимита
    access_point__ipset_shaper_timeout: 10800
    # Безлимит до 500MB, далее начинаем тормозить клиента
    access_point__traffic_limit: 524288000
     # Тормозим клиента до 200kbps
    access_point__shaping_rate: 200kbit
    access_point__ipset_acl: acl
    # Раз в 12 часов просим клиента заново пройти captive portal
    access_point__ipset_acl_timeout: 43200
    access_point__ipset_range: "{{ my_public_dhcp_range_begin }}-{{ my_public_dhcp_range_end }}"

    access_point__ipset_no_shape: no_shape
    # Клиентов из вайтлиста помним столько же, сколько разрешен доступ в сеть
    access_point__ipset_no_shape_timeout: "{{ access_point__ipset_acl_timeout }}"

    access_point__rate: 10Mbit
    access_point__nameserver: "{{ my_public_ip }}"
    access_point__http_backend_version: "0.1.11"
    access_point__http_backend_port: 8888

    ratzek_portal__main_domain: "www.{{ domain_name }}"
    ratzek_portal__grafana_domain: "grafana.{{ domain_name }}"
    ratzek_portal__library_path: /var/www/library

    minidlna:
      user: minidlna
      port: 8200
      friendly_name: Ratzek media service
      media_dirs:
        - "{{ ratzek_portal__library_path }}"
        - "{{ pavlenko_video_directory }}"

    iptables_config: |
      *filter

      :INPUT ACCEPT [0:0]
      :FORWARD DROP [0:0]
      :OUTPUT ACCEPT [0:0]

      -A FORWARD -i wlan1 -o eth0 -m set ! --match-set {{ access_point__ipset_acl }} src -j DROP -m comment --comment "No access to internet for clients not in ACL"

      -A FORWARD -i wlan1 -j SET --add-set {{ access_point__ipset_shaper }} src -m comment --comment "Register new clients with ipset table to count traffic"
      -A FORWARD -o wlan1 -j SET --add-set {{ access_point__ipset_shaper }} dst -m comment --comment "Register new clients with ipset table to count traffic"

      -A FORWARD -i wlan1 -o eth0 -m set --match-set {{ access_point__ipset_no_shape }} src -j ACCEPT -m comment --comment "Count and accept whitelisted clients traffic"
      -A FORWARD -o wlan1 -m state --state RELATED,ESTABLISHED -m set --match-set {{ access_point__ipset_no_shape }} dst -j ACCEPT -m comment --comment "Count and accept whitelisted clients traffic"

      -A FORWARD -i wlan1 -o eth0 -m set --match-set {{ access_point__ipset_shaper }} src --bytes-gt {{ access_point__traffic_limit }} -j MARK --set-mark 333 -m comment --comment "Rate limit clients which reached limit"
      -A FORWARD -i eth0 -o wlan1 -m set --match-set {{ access_point__ipset_shaper }} dst --bytes-gt {{ access_point__traffic_limit }} -j MARK --set-mark 333 -m comment --comment "Rate limit clients which reached limit"

      -A FORWARD -i wlan1 -o eth0 -m set --match-set {{ access_point__ipset_shaper }} src -j ACCEPT -m comment --comment "Count and accept clients traffic"
      -A FORWARD -o wlan1 -m state --state RELATED,ESTABLISHED -m set --match-set {{ access_point__ipset_shaper }} dst -j ACCEPT -m comment --comment "Count and accept clients traffic"

      COMMIT

      *nat

      :PREROUTING ACCEPT [0:0]

      -A PREROUTING -i wlan1 -p tcp -d {{ my_public_ip }} --dport 80 -j ACCEPT -m comment --comment "Always accept traffic to myself"
      -A PREROUTING -i wlan1 -p tcp --dport 80 -m set ! --match-set {{ access_point__ipset_acl }} src -j DNAT --to-destination {{ my_public_ip }}:81 -m comment --comment "Captive portal"

      :INPUT ACCEPT [0:0]
      :OUTPUT ACCEPT [0:0]
      :POSTROUTING ACCEPT [0:0]

      -A POSTROUTING -o eth0 -j MASQUERADE -m comment --comment "Masquerade outgoing packets"

      COMMIT

    youtube_mirror__instances:
      - youtube-pavlenko:
          directory: "{{ pavlenko_video_directory }}"
          url: https://www.youtube.com/@user-zj5ko4dm3h/videos
          cron_hour: 14

    mountain_forecast_mirror__instances:
      - putin-peak:
          directory: /var/mirrors/mountain-forecast/putin-peak
          url: https://www.mountain-forecast.com/peaks/Vladimir-Putin-Peak/forecasts/3500
          cron_hour: 9,14,18

    lepikhin_guidebook_mirror_cron_hour: 14
    lepikhin_guidebook_mirror_directory: /var/mirrors/lepikhin-guidebook
