- name: Setup Ratzek RPI
  hosts: ratzek-service
  roles:
    - role: monitoring-server
  vars:
    ntp_timezone: Asia/Bishkek

    node_exporter_web_listen_address: 127.0.0.1:9100

    prometheus_web_listen_address: 127.0.0.1:9090
    prometheus_targets:
      node:
        - targets:
            - '{{ node_exporter_web_listen_address }}'

    grafana_address: 127.0.0.1
    grafana_port: 3000
    grafana_datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        url: 'http://{{ prometheus_web_listen_address }}'
        basicAuth: false
    grafana_security:
      admin_user: admin
      admin_password: '{{ grafana_admin_password }}'

  vars_prompt:
    - name: grafana_admin_password
      prompt: Enter admin password for grafana
